import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "../../css/style.css";

import { Navbar } from "./Navbar";
import { Footer } from "./Footer";
import { PopupWidget } from "./PopupWidget";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function HomeLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={inter.className}>
                <ThemeProvider attribute="class">
                    <div className="md:px-20">
                        <Navbar />
                        <div>{children}</div>
                        <Footer />
                        <PopupWidget />
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}