import { IFAQ } from "@/types";
import { siteDetails } from "./siteDetails";

export const faqs: IFAQ[] = [
    {
        question: `How does ${siteDetails.siteName} work?`,
        answer: 'Simply enter keywords or themes related to your startup, and our AI-powered generator will create unique and brandable name ideas in seconds.',
    },
    {
        question: `Is ${siteDetails.siteName} free to use?`,
        answer: 'Yes! Our startup name generator is completely free to use, allowing you to generate unlimited name ideas without any cost.',
    },
    {
        question: 'Can I generate AI-powered startup names?',
        answer: 'Absolutely! Our tool leverages advanced AI algorithms to generate creative and unique startup names tailored to your input.',
    },
    {
        question: 'How unique are the names generated by the tool?',
        answer: 'The names generated are AI-driven and designed to be unique. However, we recommend checking domain and social media availability before finalizing your choice.',
    },
    {
        question: 'Does the tool provide industry-specific startup names?',
        answer: 'Yes! You can specify keywords related to your industry, and our AI will generate names that align with your business niche.',
    },
    {
        question: 'How can I check if a domain is available for my startup name?',
        answer: 'After generating a name, click on it to check domain availability instantly. We integrate with domain registrars to show real-time availability.',
    },
    {
        question: 'Can I see if my startup name is available on social media?',
        answer: 'Yes! Our tool can check name availability on major platforms like Twitter, Facebook, Instagram, LinkedIn, and more.',
    },
    {
        question: 'Does the tool suggest domain name variations if my name is taken?',
        answer: 'Yes! If your desired domain is unavailable, we provide alternative domain extensions and modified name suggestions.',
    },
    {
        question: 'Why is it important to check domain and social media availability?',
        answer: 'Securing a matching domain and social media handles helps in building a strong and consistent brand presence online.',
    },
    {
        question: 'How do I register a domain for my startup name?',
        answer: 'Once you find an available domain, click on the registration link to purchase it through trusted domain registrars like Namecheap or GoDaddy.',
    },
    {
        question: 'Can I generate startup names based on keywords?',
        answer: 'Yes! You can input specific words, themes, or even emotions, and our generator will create names based on your preferences.',
    },
    {
        question: 'Does the tool provide brandable or one-word startup names?',
        answer: 'Yes! You can specify your preference for short, catchy, and brandable one-word names for better memorability and impact.',
    },
    {
        question: 'Can I filter results based on length or style of the name?',
        answer: 'Absolutely! You can choose name length preferences or styles like tech-sounding, luxury, playful, or professional.',
    },
    {
        question: 'Are the generated names optimized for branding and marketing?',
        answer: 'Yes! Our AI considers branding principles, ensuring names are catchy, easy to pronounce, and marketable.',
    },
    {
        question: 'What are some tips for choosing the best startup name?',
        answer: 'Pick a name that is easy to spell, memorable, and aligns with your business. Always check domain and social media availability before finalizing.',
    }
];
